const SLUMS = [
    {
        "SLUM_ID": 1,
        "SLUM_NAME": "SHIV NANDI NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 1,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "KESHOBAG",
        "Area": 41296.616976,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 2,
        "SLUM_NAME": "ISLAMPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 1,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "BAHODAPUR",
        "Area": 66573.932403,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 3,
        "SLUM_NAME": "JANAK TAAL (KUSHWAHA MOHALLA)",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 1,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "BAHODAPUR",
        "Area": 14998.679424,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 4,
        "SLUM_NAME": "RAMAJI KA PURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 1,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "BAHODAPUR",
        "Area": 15619.490543,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 5,
        "SLUM_NAME": "GRAM BARA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 1,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "BARA",
        "Area": 97399.486635,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 6,
        "SLUM_NAME": "JATAV PURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 1,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "SHANKARPUR",
        "Area": 120050.987622,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 7,
        "SLUM_NAME": "BEES SUTRIYA NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 1,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "BAHODAPUR",
        "Area": 18510.017072,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 8,
        "SLUM_NAME": "KACHI SARAE GHOSIPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 2,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "BAHODAPUR",
        "Area": 9726.45443,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 9,
        "SLUM_NAME": "SHIVNAGAR GHOSIPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 2,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "BAHODAPUR",
        "Area": 50383.958835,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 10,
        "SLUM_NAME": "SUNAR KI BAGIA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 2,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "BAHODAPUR",
        "Area": 7970.252176,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 11,
        "SLUM_NAME": "PANCHSHEEL NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 2,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "AHUKHANA KALA",
        "Area": 4294.991947,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 12,
        "SLUM_NAME": "JADUWALA MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 2,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "AHUKHANA KALA",
        "Area": 5648.77384,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 13,
        "SLUM_NAME": "SHINDHIYA NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 2,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "AHUKHANA KALA",
        "Area": 15918.914356,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 14,
        "SLUM_NAME": "RAMPURI MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 2,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "AHUKHANA KALA",
        "Area": 20187.988637,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 15,
        "SLUM_NAME": "AMBEDKAR NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 2,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "RANIPURA",
        "Area": 3038.479336,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 16,
        "SLUM_NAME": "GHOSIPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 3,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "BAHODAPUR",
        "Area": 20669.155872,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 17,
        "SLUM_NAME": "FARRASH KHANA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 3,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "BAHODAPUR",
        "Area": 22697.346286,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 18,
        "SLUM_NAME": "SHIV NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 3,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "BAHODAPUR",
        "Area": 5313.26193,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 19,
        "SLUM_NAME": "RAMGHAD",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 3,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "BAHODAPUR",
        "Area": 18053.428384,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 21,
        "SLUM_NAME": "INDRA COLONY",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 4,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KESHOBAG A.B. ROAD",
        "Area": 31563.495126,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 22,
        "SLUM_NAME": "MEVATI MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 4,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "VILLAGE BAHODAPUR",
        "Area": 31943.61269,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 23,
        "SLUM_NAME": "BANDA GHURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 4,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "BULBUL PURA",
        "Area": 61120.156882,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 24,
        "SLUM_NAME": "GHATAMPUR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 4,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHATAMPUR",
        "Area": 7353.377734,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 25,
        "SLUM_NAME": "MIRJA PUR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 4,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHATAMPUR",
        "Area": 11028.209408,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 26,
        "SLUM_NAME": "BULBUL PURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 4,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "VILLAGE BULBUL PURA",
        "Area": 4486.038127,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 27,
        "SLUM_NAME": "CHANDRA NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 4,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GHATAMPUR",
        "Area": 14812.195186,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 28,
        "SLUM_NAME": "BADNAPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 5,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "SHANKARPUR",
        "Area": 17589.239652,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 29,
        "SLUM_NAME": "RESHAMPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 5,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "AKABARPUR",
        "Area": 117044.362151,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 30,
        "SLUM_NAME": "DAMODAR BAGH COLONY",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 5,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GRAM DAMODAR BAGH",
        "Area": 30716.798101,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 31,
        "SLUM_NAME": "KRISHNA NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 5,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MALANPUR",
        "Area": 152812.060718,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 32,
        "SLUM_NAME": "KISHAN BAG (A.B.ROAD)",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 5,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "KISHAN BAG",
        "Area": 56402.383215,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 33,
        "SLUM_NAME": "MANGLESWAR ROAD",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 6,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GRAM JAGANAPURA",
        "Area": 23242.044248,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 34,
        "SLUM_NAME": "JOSYANA MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 6,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 25602.692822,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 35,
        "SLUM_NAME": "LADHEDI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 6,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GRAM JAGANAPURA",
        "Area": 50983.626691,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 36,
        "SLUM_NAME": "MEVATI MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 6,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GRAM JAGANAPURA",
        "Area": 12517.21795,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 37,
        "SLUM_NAME": "HAVELI PICHBADA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 6,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GRAM JAGANAPURA",
        "Area": 19921.764353,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 38,
        "SLUM_NAME": "JHASI GANJ",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 6,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GRAM JAGANAPURA",
        "Area": 6790.710458,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 39,
        "SLUM_NAME": "JHAJIR KATRA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 6,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 30524.862804,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 40,
        "SLUM_NAME": "MACHII ADDI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 6,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GRAM JAGANAPURA",
        "Area": 26060.458142,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 41,
        "SLUM_NAME": "JAGNA PURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 7,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GRAM JAGANAPURA",
        "Area": 49497.885055,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 42,
        "SLUM_NAME": "INDRA NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 7,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 48177.430042,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 43,
        "SLUM_NAME": "MADAN PURA (MADAN KUI )",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 7,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 2759.848288,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 44,
        "SLUM_NAME": "LOOTPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 7,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 37610.271364,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 45,
        "SLUM_NAME": "SHARMA FARM NO.2",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 7,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "SWAJE FORM",
        "Area": 6925.366549,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 46,
        "SLUM_NAME": "SHARMA FARM NO.3",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 7,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 5740.221824,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 47,
        "SLUM_NAME": "CHODAE KE HANUMAN",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 8,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 53407.181513,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 48,
        "SLUM_NAME": "NARSINGH NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 8,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 44384.064421,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 49,
        "SLUM_NAME": "SHARMA FARM NO.1",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 8,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "SWAJE FORM",
        "Area": 9924.812968,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 50,
        "SLUM_NAME": "RANIPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 9,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 86643.536291,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 51,
        "SLUM_NAME": "RANGIANA MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 9,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 48503.474517,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 52,
        "SLUM_NAME": "POSTHI KHANA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 9,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 10186.002807,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 53,
        "SLUM_NAME": "GOLPADE",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 9,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 12811.575506,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 54,
        "SLUM_NAME": "RAJA MANDI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 9,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 103934.362549,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 55,
        "SLUM_NAME": "SODA KA KUA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 9,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 6697.692995,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 56,
        "SLUM_NAME": "MADDI KA BAZAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 9,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 9847.858558,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 57,
        "SLUM_NAME": "MAIDAI MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 9,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 11589.539105,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 58,
        "SLUM_NAME": "GOLANDAJ",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 10,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "AHUKHANA KALA",
        "Area": 39152.488595,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 59,
        "SLUM_NAME": "KESHOBAGH",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 10,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "AHUKHANA KALA",
        "Area": 24765.884218,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 60,
        "SLUM_NAME": "AAU KHANA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 10,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "AHUKHANA KALA",
        "Area": 9874.831777,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 61,
        "SLUM_NAME": "JAMA MASZID CHOWK BAZAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 10,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 7939.449442,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 62,
        "SLUM_NAME": "KASI NARESH KI GALI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 10,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GRAM RANIPURA",
        "Area": 11971.715825,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 63,
        "SLUM_NAME": "SUNAR MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 10,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "RANIPURA",
        "Area": 8112.997269,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 64,
        "SLUM_NAME": "KANOON GOYAN",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 10,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "AHUKHANA KALA",
        "Area": 12182.348249,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 65,
        "SLUM_NAME": "TAMESHWAR MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 10,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GRAM JAGANAPURA",
        "Area": 3310.326773,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 66,
        "SLUM_NAME": "HATHA KHANA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 10,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "AHUKHANA",
        "Area": 5548.166581,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 67,
        "SLUM_NAME": "GOSHPURA NO 1",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 11,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 8998.764152,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 68,
        "SLUM_NAME": "GOSHPURA NO2",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 11,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 10106.54079,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 69,
        "SLUM_NAME": "RASULA BAD",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 12,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 6498.93399,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 70,
        "SLUM_NAME": "KOTAWALA MOHALLA ",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 13,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "RAMTAPURA",
        "Area": 3725.253232,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 71,
        "SLUM_NAME": "PACHEE PADA ",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 13,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "RAMTAPURA",
        "Area": 5409.714142,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 72,
        "SLUM_NAME": "KHIDKI MOHALLA ",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 13,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "RAMTAPURA",
        "Area": 1458.390436,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 73,
        "SLUM_NAME": "HORIPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 13,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "RAMTAPURA",
        "Area": 7693.775344,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 74,
        "SLUM_NAME": "GUDRI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 14,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "AHUKHANA KHURD",
        "Area": 4606.725144,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 75,
        "SLUM_NAME": "NOORGANJ",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 14,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "AHUKHANA KHURD",
        "Area": 13684.031318,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 76,
        "SLUM_NAME": "KWAJA NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 14,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "RAMTAPURA",
        "Area": 15371.48289,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 77,
        "SLUM_NAME": "RAMTAPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 14,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "RAMTAPURA",
        "Area": 51019.429081,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 78,
        "SLUM_NAME": "KHWAJA KANOOUN",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 14,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "RAMTAPURA",
        "Area": 24760.702221,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 79,
        "SLUM_NAME": "JATI KI LANE",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 15,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 20487.984667,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 80,
        "SLUM_NAME": "HARIZAN BASTI ( LINE NO.5)",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 15,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 8965.55558,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 81,
        "SLUM_NAME": "NEW SANJAY NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 15,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GADHAIPURA",
        "Area": 60220.823158,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 82,
        "SLUM_NAME": "GADAI PURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 15,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GADHAIPURA",
        "Area": 147613.789529,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 83,
        "SLUM_NAME": "NEW COLONY TWO",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 16,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 23508.190196,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 84,
        "SLUM_NAME": "NEW COLONY ONE",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 16,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 21502.759776,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 85,
        "SLUM_NAME": "CHANDANPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 16,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 25564.710077,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 86,
        "SLUM_NAME": "RESHAM MILL BASTI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 16,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 14149.485534,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 87,
        "SLUM_NAME": "ANAND NAGAR (CHAMDA MILL)",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 17,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 22454.762635,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 88,
        "SLUM_NAME": "ARA MILL ( HARIJAN BASTI)",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 17,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 6145.849033,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 89,
        "SLUM_NAME": "3V COLONY LAL QUATER",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 17,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 9736.450545,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 90,
        "SLUM_NAME": "NEW KANCH MILL",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 17,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 10282.356079,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 91,
        "SLUM_NAME": "ADARSH NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 18,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "JADERUA KALAH",
        "Area": 24029.696667,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 92,
        "SLUM_NAME": "RUSHALPUR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 18,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "JADERUA KALAH",
        "Area": 8210.92936,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 93,
        "SLUM_NAME": "JADERUA KALAH",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 19,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "JADERUA KALAH",
        "Area": 55382.830598,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 94,
        "SLUM_NAME": "RACHANA NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 19,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "JADERUA KHURD",
        "Area": 23878.971715,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 95,
        "SLUM_NAME": "VIVEK NAGAR ",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 21,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 33024.159344,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 96,
        "SLUM_NAME": "PANCHSHEEL NAGAR ",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 21,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 27031.15202,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 97,
        "SLUM_NAME": "MELLA DULPUR ",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 21,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 31707.951974,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 98,
        "SLUM_NAME": "SANTI NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 21,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 2382.975921,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 99,
        "SLUM_NAME": "BAGIYA HANUMAN NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 21,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 31632.029356,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 100,
        "SLUM_NAME": "BASTI GODHAM",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 22,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 19696.603116,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 101,
        "SLUM_NAME": "SHIDHESHWAR NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 22,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 11256.305461,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 102,
        "SLUM_NAME": "KHALEEFA COLONY",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 22,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 2556.110385,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 103,
        "SLUM_NAME": "GOPALPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 22,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MEHARA",
        "Area": 4523.467085,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 104,
        "SLUM_NAME": "SHIDARTH NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 22,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 5233.866461,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 105,
        "SLUM_NAME": "NADI PAR TAL",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 23,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 15178.743984,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 106,
        "SLUM_NAME": "GALLA KOTHAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 23,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MEHARA",
        "Area": 26518.674779,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 107,
        "SLUM_NAME": "AMBEDKAR NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 23,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 4592.47123,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 108,
        "SLUM_NAME": "SHRI NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 23,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 73547.020049,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 109,
        "SLUM_NAME": "HARIJAN BASTI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 23,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 2889.932219,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 110,
        "SLUM_NAME": "LEATHER FECTORY",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 25,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 20671.346242,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 111,
        "SLUM_NAME": "SHEETLA COLONY",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 25,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 28353.621231,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 112,
        "SLUM_NAME": "TIKINOYA MORAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 26,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 17720.111528,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 113,
        "SLUM_NAME": "HARIJAN BASTI HARIJAN GURUDWARA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 26,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 6902.616471,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 114,
        "SLUM_NAME": "KHATEEK MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 26,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 6575.0602,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 115,
        "SLUM_NAME": "HANUMAN COLONY MORAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 26,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "JADERUA KALAH",
        "Area": 4625.93532,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 116,
        "SLUM_NAME": "TYAGI NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 26,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 17339.055019,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 117,
        "SLUM_NAME": "PEETAL KARKHANA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 26,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 13780.333435,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 118,
        "SLUM_NAME": "KACHERI PARUSRAM",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 26,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 5881.912651,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 119,
        "SLUM_NAME": "VINAY COLONY",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 26,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "BAHODAPUR",
        "Area": 6636.040123,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 120,
        "SLUM_NAME": "GHASS MANDI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 26,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 2744.052421,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 121,
        "SLUM_NAME": "RAM NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 27,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 13858.109536,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 122,
        "SLUM_NAME": "HARNAMPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 28,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MEHARA",
        "Area": 21246.341211,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 123,
        "SLUM_NAME": "BHEEM NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 28,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 30941.865528,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 124,
        "SLUM_NAME": "PHULE NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 28,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MEHARA",
        "Area": 32318.361795,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 125,
        "SLUM_NAME": "KUMHARAPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 28,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MORAR",
        "Area": 31913.120048,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 126,
        "SLUM_NAME": "MAHAL GAON (KAROULI MATA)",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 29,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MAHAL GAON",
        "Area": 214255.452017,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 127,
        "SLUM_NAME": "GUJRATI MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 31,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GHOSPURA",
        "Area": 6156.306359,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 128,
        "SLUM_NAME": "LAXMANPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 31,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MAHAL GAON",
        "Area": 22400.534516,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 129,
        "SLUM_NAME": "MARI MATA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 32,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "AHUKHANA KHURD",
        "Area": 30530.138653,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 130,
        "SLUM_NAME": "MAHAL GAON ( MARI MATA)",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 32,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "AHUKHANA KHURD",
        "Area": 11731.435155,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 131,
        "SLUM_NAME": "RAVI DAS NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 33,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 16717.473014,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 132,
        "SLUM_NAME": "DONGARPUR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 33,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 12608.334059,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 133,
        "SLUM_NAME": "LAXMAN TALIYA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 33,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 7735.850645,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 134,
        "SLUM_NAME": "KHATEEK MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 33,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 5440.472185,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 135,
        "SLUM_NAME": "KHALASIPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 33,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 25965.157807,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 136,
        "SLUM_NAME": "PIYAU WALI GALI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 33,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 6015.869533,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 137,
        "SLUM_NAME": "PARDI MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 34,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 14458.284931,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 138,
        "SLUM_NAME": "SHEKH KI BAGIYA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 35,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 22487.128913,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 139,
        "SLUM_NAME": "SWARNREKHA NALA JIWAJI GANJ",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 35,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 18926.384568,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 140,
        "SLUM_NAME": "SUBEY KI GOTH",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 35,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 16503.329483,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 141,
        "SLUM_NAME": "SANTI NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 35,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 11597.667587,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 142,
        "SLUM_NAME": "RASSI WALA MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 35,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 15390.568804,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 143,
        "SLUM_NAME": "DALIYA WALA MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 35,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 1712.747729,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 144,
        "SLUM_NAME": "GANJ WALA MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 35,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 5268.10132,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 145,
        "SLUM_NAME": "DHOBI GHAT NO .2",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 36,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 10924.859098,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 146,
        "SLUM_NAME": "DHOBI GHAT NO .1",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 36,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 3580.704698,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 147,
        "SLUM_NAME": "BAKRA MANDI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 36,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 5872.118065,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 148,
        "SLUM_NAME": "SATYA NARAYAN KI TEKRI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 36,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 11492.09152,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 149,
        "SLUM_NAME": "MADHOU NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 37,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 71883.363349,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 150,
        "SLUM_NAME": "SANJAY NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 37,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 173874.883896,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 151,
        "SLUM_NAME": "NIMBAJI KI KHO",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 37,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 295782.387078,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 152,
        "SLUM_NAME": "NAYA PURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 37,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 5453.549577,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 153,
        "SLUM_NAME": "JAGRITI NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 37,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 41507.670542,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 154,
        "SLUM_NAME": "TITURIMA COLONY",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 37,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 5785.383826,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 155,
        "SLUM_NAME": "SHATI NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 37,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 3201.201496,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 156,
        "SLUM_NAME": "AMAN KA PURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 37,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 8127.341472,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 157,
        "SLUM_NAME": "GOL PAHADIYA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 38,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 16994.93106,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 158,
        "SLUM_NAME": "GUPTESWAR PAHADI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 38,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 54399.238316,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 159,
        "SLUM_NAME": "AMRA PAHAD",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 38,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 43553.536469,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 160,
        "SLUM_NAME": "RAJA GAS GODAM",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 38,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 41296.679058,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 161,
        "SLUM_NAME": "GANESH MANDIR RAJA GAS GODAM",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 38,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 95616.039651,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 162,
        "SLUM_NAME": "HARKOTA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 38,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 100494.589374,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 163,
        "SLUM_NAME": "BHINYO KA PURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 38,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 36146.894091,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 164,
        "SLUM_NAME": "LAL KUWAR KA PURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 38,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 28535.859016,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 165,
        "SLUM_NAME": "MEHRA SAHAB KI TALAIYA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 38,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 9976.854119,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 166,
        "SLUM_NAME": "KAMBAL KENDRA HARIZAN BASTI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 39,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 9463.561933,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 167,
        "SLUM_NAME": "SATH BHAI KI GOTH",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 39,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 11302.114063,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 168,
        "SLUM_NAME": "JATAR GALI SWARNREKHA NALA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 39,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 31965.995726,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 169,
        "SLUM_NAME": "DHOLI BUA KA PULL",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 39,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 19472.143618,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 170,
        "SLUM_NAME": "BAI SAHAB KI PARED",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 39,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 8841.990831,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 171,
        "SLUM_NAME": "BHURE BABA KI BASTI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 40,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 15295.902565,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 172,
        "SLUM_NAME": "GADI WALA MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 40,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 6484.402496,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 173,
        "SLUM_NAME": "BHEISHA CHOKEY",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 40,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 2339.704338,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 174,
        "SLUM_NAME": "TOPE WALA MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 41,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 50925.714567,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 175,
        "SLUM_NAME": "KHURJA WALA MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 44,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 11259.217105,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 176,
        "SLUM_NAME": "JATAVPURA  (LALITPUR COLONY )",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 45,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "LALITPUR",
        "Area": 9181.90657,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 177,
        "SLUM_NAME": "TAPPU MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 46,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 34753.32583,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 178,
        "SLUM_NAME": "TELI KI BAZARIYA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 46,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 11469.244012,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 179,
        "SLUM_NAME": "KAMATI PURA JATAV MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 47,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 30607.083138,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 180,
        "SLUM_NAME": "KABUTER KI HATH",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 47,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 13820.845106,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 181,
        "SLUM_NAME": "ROXY PULL LAKADE KHANA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 47,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 11575.292687,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 182,
        "SLUM_NAME": "UTAR KHANA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 47,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 5350.704525,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 183,
        "SLUM_NAME": "KADAM SAHAB KA BADA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 48,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 4494.853015,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 184,
        "SLUM_NAME": "JAMBUR KHANA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 48,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 8762.620452,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 185,
        "SLUM_NAME": "HEM SINGH KI PARED",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 48,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 8852.884829,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 186,
        "SLUM_NAME": "HAIDAR GANJ",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 48,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 6829.806686,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 187,
        "SLUM_NAME": "AAPA GANJ (KARIGARO KA MOHALLA )",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 48,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 5882.772382,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 188,
        "SLUM_NAME": "HARI ANNA KA PURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 49,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 8492.533608,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 189,
        "SLUM_NAME": "BANJARA SAHA KA NALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 49,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 12394.076447,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 190,
        "SLUM_NAME": "KALA SAIYAD",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 49,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 8414.749696,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 191,
        "SLUM_NAME": "NAYAPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 49,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KOTA LASHKAR",
        "Area": 5590.319708,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 192,
        "SLUM_NAME": "IMALI NAKA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 51,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 20665.727822,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 193,
        "SLUM_NAME": "JATAV MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 51,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 8585.953762,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 194,
        "SLUM_NAME": "SIKANDAR KAMPU",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 51,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 27969.679939,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 195,
        "SLUM_NAME": "APA GANJ  (HATHI KHANA)",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 51,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 29578.896734,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 196,
        "SLUM_NAME": "GUDI NAKA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 52,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GUDHI",
        "Area": 13415.949919,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 197,
        "SLUM_NAME": "PYAGA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 52,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 83093.636918,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 198,
        "SLUM_NAME": "NADARIYA WALI MATA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 52,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GUDHI",
        "Area": 311080.719936,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 199,
        "SLUM_NAME": "GUDI UPAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 52,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GUDHI",
        "Area": 174068.86,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 200,
        "SLUM_NAME": "BILGAIYA KA PURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 52,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GUDHI",
        "Area": 14084.547091,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 201,
        "SLUM_NAME": "LAKARKHANA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 53,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 9608.704782,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 202,
        "SLUM_NAME": "MUNSHIYON KA MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 53,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 13910.21988,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 203,
        "SLUM_NAME": "DEV NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 53,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 5685.902229,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 204,
        "SLUM_NAME": "KARWARI MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 53,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 6476.947399,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 205,
        "SLUM_NAME": "NAYAPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 53,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 11910.760637,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 206,
        "SLUM_NAME": "ENGALE KI GOTH",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 53,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 7951.182008,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 207,
        "SLUM_NAME": "GANJIWALA MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 53,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 10364.842325,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 208,
        "SLUM_NAME": "PAN PATTE KI GOTH",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 53,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 9679.331634,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 209,
        "SLUM_NAME": "RISHI NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 53,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 6428.555932,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 210,
        "SLUM_NAME": "SURYA NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 53,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 7623.001508,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 211,
        "SLUM_NAME": "HARIJAN BASTI ( JAWAHAR COLONY)",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 54,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 4250.575824,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 212,
        "SLUM_NAME": "ARMY KI BAJRIYA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 54,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GUDHI",
        "Area": 2646.527592,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 213,
        "SLUM_NAME": "CHANA KOTHAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 54,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 4531.347154,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 214,
        "SLUM_NAME": "AWADPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 55,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GUDHI",
        "Area": 23445.60159,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 215,
        "SLUM_NAME": "KHAJANCHI BABA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 55,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GUDHI",
        "Area": 151977.207255,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 216,
        "SLUM_NAME": "MUDIA PAHAD",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 56,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MUDHIYA PAHAD",
        "Area": 43215.697284,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 217,
        "SLUM_NAME": "GADE WALA MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 56,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MUDHIYA PAHAD",
        "Area": 21936.852738,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 218,
        "SLUM_NAME": "PARDI MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 56,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MUDHIYA PAHAD",
        "Area": 40518.789915,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 219,
        "SLUM_NAME": "GNJI KHO ( GALI NO. 1)",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 56,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MUDHIYA PAHAD",
        "Area": 33731.792918,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 220,
        "SLUM_NAME": "LABHED PURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 56,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MUDHIYA PAHAD",
        "Area": 3853.981703,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 221,
        "SLUM_NAME": "NAKA CHANDRA BADNI  (GALI NO. 2,4,5)",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 56,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MUDHIYA PAHAD",
        "Area": 13233.175476,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 222,
        "SLUM_NAME": "DEV NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 56,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MUDHIYA PAHAD",
        "Area": 43689.453475,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 223,
        "SLUM_NAME": "OF KI BAGIYA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 57,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "LALITPUR",
        "Area": 20967.426615,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 224,
        "SLUM_NAME": "RANIPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 57,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "LALITPUR",
        "Area": 13895.460418,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 225,
        "SLUM_NAME": "NIRDHAN NAGAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 58,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "CITY LASHKAR",
        "Area": 34735.61183,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 226,
        "SLUM_NAME": "LABHAD PURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 59,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MUDHIYA PAHAD",
        "Area": 28834.797853,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 227,
        "SLUM_NAME": "VICKY FACTORY",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 59,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MAHAL GAON",
        "Area": 27438.948876,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 228,
        "SLUM_NAME": "LALIYA PURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 59,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "LALIYA PURA",
        "Area": 48763.727563,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 229,
        "SLUM_NAME": "KHOTI GAO",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 59,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KEADARPUR",
        "Area": 38190.991606,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 230,
        "SLUM_NAME": "BADEE MAREAYA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 59,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KEADARPUR",
        "Area": 18080.80096,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 231,
        "SLUM_NAME": "CHOTI MADIYA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 59,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "KEADARPUR",
        "Area": 30588.387467,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 232,
        "SLUM_NAME": "NEEM CHANDOHA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 59,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "NEEM CHANDOHA",
        "Area": 30030.277372,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 233,
        "SLUM_NAME": "PARDI MOHALLLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 59,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MUDHIYA PAHAD",
        "Area": 6943.293896,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 234,
        "SLUM_NAME": "MARGHAT BALI PHADRI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 60,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "MAHAL GAON",
        "Area": 159242.597458,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 235,
        "SLUM_NAME": "COTEY KI SARAY",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 60,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "BHATKHADI",
        "Area": 22096.675435,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 236,
        "SLUM_NAME": "HURAWALI",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 60,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MEHARA",
        "Area": 81424.865948,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 237,
        "SLUM_NAME": "HARKHEDA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 60,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "MEHARA",
        "Area": 50432.869897,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 238,
        "SLUM_NAME": "DONGARPUR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 60,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "DONGARPUR",
        "Area": 31270.572894,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 239,
        "SLUM_NAME": "SIROL COLONY",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 60,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "SIROL",
        "Area": 30462.65412,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 240,
        "SLUM_NAME": "NEW MEHARA COLONY",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 60,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GRAM MEHARA",
        "Area": 129912.050777,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 241,
        "SLUM_NAME": "ALAPUR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 60,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "ALAPUR",
        "Area": 25787.137818,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 242,
        "SLUM_NAME": "OHADPUR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 60,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "OHADPUR",
        "Area": 40040.716081,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 243,
        "SLUM_NAME": "GHOSIPURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 60,
        "SLUM_TYPE": "NON-NOTIFIED",
        "VILLAGE": "GRAM MORAR",
        "Area": 18920.946873,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 244,
        "SLUM_NAME": "BALE KA PURA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 60,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "GUDA",
        "Area": 66760.183541,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 245,
        "SLUM_NAME": "KASAI MOHALLA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 14,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "NOT_KNOWN",
        "Area": 4159.054417,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 246,
        "SLUM_NAME": "ASHOK COLONY MORAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 22,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "NOT_KNOWN",
        "Area": 12174.512512,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 247,
        "SLUM_NAME": "ROSHANI GHAR",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 57,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "NOT_KNOWN",
        "Area": 3927.072712,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 248,
        "SLUM_NAME": "NIMVALKER KI GOTHE",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 46,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "NOT_KNOWN",
        "Area": 4238.31148,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 249,
        "SLUM_NAME": "GUDA",
        "STATE_CODE": 23,
        "DIST_CODE": 407,
        "ULB_CODE": 101,
        "ULB_NAME": "GWALIOR",
        "CITY_TOWN_CODE": 474001,
        "WARD_NO": 55,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "NOT_KNOWN",
        "Area": 49917.004686,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    },
    {
        "SLUM_ID": 250,
        "SLUM_NAME": "GANJ",
        "STATE_CODE": 9,
        "DIST_CODE": 162,
        "ULB_CODE": 301,
        "ULB_NAME": "LUCKNOW",
        "CITY_TOWN_CODE": 226021,
        "WARD_NO": 80,
        "SLUM_TYPE": "NOTIFIED",
        "VILLAGE": "JANKIPURAM",
        "Area": 5000,
        "LAND_OWNERSHIP": "",
        "TOTAL_HOUSE_HOLDS": ""
    }
]
